apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: myblog-ns
type: Opaque
data:
  MONGO_URI: bW9uZ29kYjovL2FkbWluOmFkbWluQDEyM0Btb25nby1zZXJ2aWNlOjI3MDE3L215YmxvZz9hdXRoU291cmNlPWFkbWlu
  
